# Generated by Django 6.0.2 on 2026-03-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='school_name',
            field=models.CharField(choices=[('MPSTME', 'Mukesh Patel School of Technology Management & Engineering'), ('ASMSOC', 'Anil Surendra Modi School of Commerce'), ('SBM', 'School of Business Management'), ('SAMSOE', 'Sarla Anil Modi School of Economics'), ('SPPSPTM', 'Shobhaben Pratapbhai Patel School of Pharmacy & Technology Management'), ('KPMSOL', 'Kirit P. Mehta School of Law'), ('SDSOS', 'Sunandan Divatia School of Science'), ('SOD', 'School of Design'), ('SOHM', 'School of Hospitality Management'), ('SOMSR', 'School of Mathematical Sciences'), ('SOPC', 'School of Performing Arts'), ('STME', 'School of Technology Management & Engineering')], default='MPSTME', max_length=10),
        ),
    ]
